// <auto-generated />
using BasketballClub_Rest.Domain;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BasketballClub_Rest.Migrations
{
    [DbContext(typeof(BCContext))]
    [Migration("20211204225719_First")]
    partial class First
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.10")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BasketballClub_Rest.Domain.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserID");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("BasketballClub_Rest.Domain.Coach", b =>
                {
                    b.HasBaseType("BasketballClub_Rest.Domain.User");

                    b.Property<int>("MyProperty")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("YearsOfExperience")
                        .HasColumnType("int");

                    b.ToTable("Coaches");
                });

            modelBuilder.Entity("BasketballClub_Rest.Domain.Operator", b =>
                {
                    b.HasBaseType("BasketballClub_Rest.Domain.User");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("Operators");
                });

            modelBuilder.Entity("BasketballClub_Rest.Domain.Coach", b =>
                {
                    b.HasOne("BasketballClub_Rest.Domain.User", null)
                        .WithOne()
                        .HasForeignKey("BasketballClub_Rest.Domain.Coach", "UserID")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BasketballClub_Rest.Domain.Operator", b =>
                {
                    b.HasOne("BasketballClub_Rest.Domain.User", null)
                        .WithOne()
                        .HasForeignKey("BasketballClub_Rest.Domain.Operator", "UserID")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
